/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1003776_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1003776_1[] = { "Coffee", "MPBC", "Vinegar" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1003776_2_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_1003776_2_axes_size = 3;
ei_dsp_config_flatten_t ei_dsp_config_1003776_2 = {
    2, // uint32_t blockId
    1, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    false, // boolean skewness
    false, // boolean kurtosis
    3 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_1003776_2[18] = { 27784.57702118845, 27737.839393939394, 27832.575757575756, 27784.62774029356, 28.304431044332908, 27788.77196081913, 114.55060598590609, 103.91515151515152, 124.33484848484848, 115.02942406652552, 6.294289603084326, 114.47662461446316, 475.2446467081706, 390.5651515151515, 563.1409090909091, 476.8507698059082, 34.391429363597524, 474.079806356719 };
const float ei_dn_standard_scaler_scale_1003776_2[18] = { 0.0008666537215203527, 0.0008684087612435181, 0.0008618805791852279, 0.0008666524516614936, 0.02225570989915135, 0.0008667701349545454, 0.014482202142066278, 0.017660355280323583, 0.012549438004790187, 0.014360249435408319, 0.0812082179704297, 0.014726193834013005, 0.005572201100642848, 0.006061557410568253, 0.004641073495691147, 0.005556816412579655, 0.04364342563351763, 0.005576724575849279 };
const float ei_dn_standard_scaler_var_1003776_2[18] = { 1331400.719934186, 1326024.6802662981, 1346188.2957759423, 1331404.6215956528, 2018.9106388368782, 1331043.1106545993, 4767.9400912269, 3206.277649219465, 6349.674240128563, 4849.266283420271, 151.63520372663888, 4611.253255179312, 32206.715473343404, 27216.454846189165, 46426.196811294736, 32385.29836875705, 525.0036668671628, 32154.488689918686 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1003776_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1003776_2,
    .mean_data_len = 18,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1003776_2,
    .scale_data_len = 18,
    .var_data = (float *)ei_dn_standard_scaler_var_1003776_2,
    .var_data_len = 18
};
ei_data_normalization_t ei_data_normalization_config_1003776_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_1003776_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1003776_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1003776_1[ei_dsp_blocks_1003776_1_size] = {
    { // DSP block 2
        2,
        18, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_1003776_2, // pointer to config struct
        ei_dsp_config_1003776_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1003776_2_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_1003776_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1003776_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1003776_3_init,
    .model_invoke = &tflite_learn_1003776_3_invoke,
    .model_reset = &tflite_learn_1003776_3_reset,
    .model_input = &tflite_learn_1003776_3_input,
    .model_output = &tflite_learn_1003776_3_output,
};

const uint8_t ei_output_tensors_indices_1003776_3[1] = { 0 };
const uint8_t ei_output_tensors_size_1003776_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1003776_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_1003776_3,
    .output_tensors_size = ei_output_tensors_size_1003776_3,
    .quantized = 0,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1003776_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1003776_1_size = 1;
const uint32_t ei_learning_block_1003776_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_1003776_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1003776_1[ei_learning_blocks_1003776_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1003776_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1003776_3_inputs,
        ei_learning_block_1003776_3_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_1003776_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1003776_1[ei_postprocessing_blocks_1003776_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_1003776_1_size = 0;

uint32_t *freeform_outputs_1003776_1 = nullptr;

const ei_impulse_t impulse_1003776_1 = {
    .project_id = 1003776,
    .project_owner = "Jreiber",
    .project_name = "Air Quality Detector ML",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 7,

    .nn_input_frame_size = 18,
    .raw_sample_count = 30,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 30 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1000,
    .frequency = 1,

    .dsp_blocks_size = ei_dsp_blocks_1003776_1_size,
    .dsp_blocks = ei_dsp_blocks_1003776_1,

    .learning_blocks_size = ei_learning_blocks_1003776_1_size,
    .learning_blocks = ei_learning_blocks_1003776_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1003776_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1003776_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "sgp40Raw + vocIndex + micsRaw",
    .slice_size = (30/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_1003776_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1003776_1_size,
    .freeform_outputs = freeform_outputs_1003776_1
};

ei_impulse_handle_t impulse_handle_1003776_1 = ei_impulse_handle_t( &impulse_1003776_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1003776_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1003776_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1003776_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1003776_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
