/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 26.05.2026 10:58:26

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1488;
#else
constexpr int kTensorArenaSize = 464;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,18 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data1[3*10] = { 
  0.025500703603029251, -1.2291518449783325, -0.051524829119443893, -1.2763837575912476, 2.054246187210083, -0.56160807609558105, 0.41987991333007812, -1.954065203666687, -1.6371326446533203, 3.8052210807800293, 
  0.6975443959236145, 3.1880507469177246, -0.27139467000961304, -1.2378226518630981, -0.76044934988021851, 2.5646488666534424, 1.9543638229370117, -0.69520300626754761, 0.90362441539764404, -0.51016473770141602, 
  -1.0264801979064941, -0.80822610855102539, 2.5678873062133789, 1.2758461236953735, -1.2185183763504028, -1.2714289426803589, -1.5812127590179443, 0.25408735871315002, 0.49008503556251526, -0.7352944016456604, 
};
const TfArray<2, int> tensor_dimension1 = { 2, { 3,10 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data2[10*20] = { 
  0.61878019571304321, -0.16058677434921265, -0.24792805314064026, 0.14991621673107147, 0.34455132484436035, 0.53019392490386963, 0.40245726704597473, 0.026488795876502991, -0.078942850232124329, -0.13766464591026306, 0.23564186692237854, 0.077180318534374237, 0.12538132071495056, 0.85585778951644897, 0.49514943361282349, -0.036776870489120483, 0.04721103236079216, 0.076440267264842987, 0.013360880315303802, 0.26950857043266296, 
  0.049305807799100876, -0.51855647563934326, -0.32285240292549133, 2.0278177261352539, 0.42544704675674438, -0.44549188017845154, -0.65269762277603149, -0.035210404545068741, 0.038806561380624771, 0.52043241262435913, 0.32434254884719849, -0.47571608424186707, -0.092413276433944702, 0.39834210276603699, 0.20876550674438477, 0.6828010082244873, -0.24322237074375153, 0.66634702682495117, -0.39007365703582764, -0.12099985033273697, 
  0.51607924699783325, -0.57674187421798706, 0.38765725493431091, -0.58505946397781372, -0.33449834585189819, -0.44811373949050903, -0.60385388135910034, -0.2713642418384552, -0.61186319589614868, -0.49837797880172729, -0.70858335494995117, -0.463523268699646, -0.75886672735214233, -0.72482532262802124, -0.55456525087356567, -0.77264070510864258, -0.51203888654708862, -1.0327601432800293, -0.87399214506149292, -0.54883861541748047, 
  -0.075022406876087189, 0.42302027344703674, 1.6401820182800293, -0.13377536833286285, -0.47133558988571167, 0.35369953513145447, 0.24298050999641418, -0.3247094452381134, -0.13753817975521088, 0.049068540334701538, 0.027705514803528786, 1.2232342958450317, -0.19861537218093872, -0.39487707614898682, -0.28433185815811157, -0.17882959544658661, -0.33693495392799377, -0.14544899761676788, 0.58278632164001465, 0.047147046774625778, 
  0.1922718733549118, 0.0878157839179039, -0.4712693989276886, -0.59401732683181763, 0.12019786983728409, 0.37293893098831177, -0.46282592415809631, 1.7140202522277832, 0.18054009974002838, -0.30826607346534729, 1.0901584625244141, 0.013905766420066357, -0.4782310426235199, 0.060767807066440582, 0.63775068521499634, -0.44704440236091614, -0.45252072811126709, 0.98502552509307861, 1.0218018293380737, 1.5740774869918823, 
  -0.30657628178596497, 0.10663063079118729, -0.56712329387664795, 1.859284520149231, 0.20113153755664825, -0.20199683308601379, -0.12357032299041748, 0.56378930807113647, -0.044676117599010468, 0.2394392341375351, 1.8570019006729126, 0.20635870099067688, -0.034620903432369232, 0.27736514806747437, -0.044162672013044357, 0.30428287386894226, -0.068649992346763611, 1.2605170011520386, -0.34536334872245789, 0.062856525182723999, 
  1.2624015808105469, 0.15293127298355103, -0.54921495914459229, 0.063581161201000214, 1.3719758987426758, 0.38343408703804016, -0.19706469774246216, 0.48862963914871216, 0.46505299210548401, 0.46293994784355164, 1.0283516645431519, -0.27849271893501282, -0.27355122566223145, 0.42761170864105225, 0.96908372640609741, 0.20225542783737183, 0.58560276031494141, 0.44068333506584167, -0.12667597830295563, 0.26262062788009644, 
  -0.066380806267261505, 0.76940047740936279, 1.5120775699615479, 0.19027486443519592, -0.078307963907718658, 0.72067022323608398, 1.7015537023544312, -0.49011972546577454, 0.24232588708400726, -0.066223554313182831, -0.50882405042648315, 1.4803448915481567, 1.1928420066833496, 0.021207276731729507, -0.23143000900745392, 0.34370756149291992, 0.74648654460906982, 0.0050847167149186134, 0.56875425577163696, 0.31744536757469177, 
  0.4348551332950592, 0.59920471906661987, 1.0000162124633789, 1.6141911745071411, 0.017863862216472626, 0.088956408202648163, -0.05029856413602829, -0.24716615676879883, -0.26698988676071167, 0.77154058218002319, 0.072479404509067535, 0.46422281861305237, 0.86015695333480835, 0.19108118116855621, -0.027458995580673218, 1.8039294481277466, 0.095279030501842499, 0.3376176655292511, -0.22507384419441223, -0.47589462995529175, 
  0.43241304159164429, -0.17982397973537445, -0.33377519249916077, -0.4915909469127655, 0.91186702251434326, 0.522552490234375, -0.35493028163909912, 1.3590060472488403, 0.87922990322113037, -0.74985897541046143, 0.24612264335155487, 0.034727342426776886, -0.67531973123550415, -0.154997318983078, 1.0658339262008667, -0.30981400609016418, -0.41176924109458923, 0.62946945428848267, 0.40742886066436768, 1.5386515855789185, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 10,20 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data3[10] = { 0.095647417008876801, 0.047978293150663376, -0.00052314030472189188, -0.12113334983587265, -0.00053868256509304047, 0.064561948180198669, 0.23583181202411652, -0.12066004425287247, 0.085466787219047546, -0.019948516041040421, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data4[20] = { 0.24763840436935425, -0.032861921936273575, -0.093394525349140167, -0.0033500471618026495, 0.154242143034935, 0.079058051109313965, -0.061599746346473694, 0.044584594666957855, 0.0076123913750052452, 0.069793105125427246, 0.040167544037103653, -0.070539422333240509, -0.069120600819587708, 0.048858702182769775, 0.086773812770843506, 0.050164364278316498, 0.1320679783821106, 0.067184954881668091, -0.045091517269611359, -0.00027534319087862968, };
const TfArray<1, int> tensor_dimension4 = { 1, { 20 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) float tensor_data5[3] = { -0.026532197371125221, 0.13015985488891602, -0.088144265115261078, };
const TfArray<1, int> tensor_dimension5 = { 1, { 3 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data6[20*18] = { 
  0.048918839544057846, -0.0053352238610386848, 0.0099313575774431229, 0.32560521364212036, 1.7164969444274902, 0.20734278857707977, 0.058962713927030563, -0.25237813591957092, 0.0036723800003528595, -0.25384888052940369, 0.10236439108848572, -0.046019989997148514, -0.3629395067691803, -0.81792211532592773, 0.094825096428394318, 0.080496303737163544, 0.13260269165039062, 0.17348779737949371, 
  -0.43396785855293274, -0.19227856397628784, 0.053358178585767746, -0.14042830467224121, -0.032412935048341751, -0.13005475699901581, 0.33394715189933777, 0.30177175998687744, 0.40586251020431519, 0.58582258224487305, 0.12216208875179291, 0.43995934724807739, 0.019498903304338455, 0.072063945233821869, 0.13526415824890137, -0.1824728399515152, 0.45710015296936035, 0.19128364324569702, 
  -0.18113051354885101, -0.40639954805374146, -0.58994936943054199, -0.55478018522262573, 0.85074222087860107, -0.50492656230926514, 0.20948608219623566, -0.0098682856187224388, 0.59482628107070923, -0.07689531147480011, 0.2646544873714447, -0.028226157650351524, -0.04312332347035408, -0.078498415648937225, -0.29389369487762451, 0.55710726976394653, 0.59716951847076416, 0.31880006194114685, 
  -0.033768046647310257, 0.80100423097610474, 0.10229264199733734, 0.87969547510147095, 0.14768341183662415, 0.88854676485061646, -0.23100726306438446, 0.11146380752325058, 0.088376536965370178, -0.40455693006515503, 0.50413548946380615, 0.078725643455982208, 0.79401153326034546, 0.62574994564056396, 0.56020194292068481, 0.30966430902481079, -0.54857558012008667, 0.11539939045906067, 
  0.63362061977386475, 0.28442010283470154, 0.21613119542598724, -0.15383835136890411, -0.79784458875656128, -0.19332258403301239, -0.051798507571220398, -0.15755240619182587, -0.50288659334182739, -0.13255244493484497, -0.79395073652267456, -0.23691757023334503, -0.25528565049171448, -0.013405677862465382, 0.29124873876571655, 0.11054739356040955, 0.70668858289718628, 0.25788295269012451, 
  0.014725194312632084, 0.28648987412452698, 0.1469159722328186, 0.08065379410982132, 0.38203591108322144, -0.12042585760354996, 0.15108799934387207, 0.40306493639945984, 0.017577573657035828, 0.18238279223442078, -0.19925616681575775, 0.0076088756322860718, -0.54394698143005371, 0.11107637733221054, -0.18609966337680817, -0.31595173478126526, -0.45965364575386047, -0.19440536201000214, 
  0.10009119659662247, -0.1542033851146698, -0.17457480728626251, -0.22038803994655609, -0.26838478446006775, -0.32486787438392639, -0.0040598064661026001, 0.32704326510429382, 0.015304894186556339, 0.14600376784801483, 0.2818845808506012, 0.083842359483242035, -0.079985484480857849, -0.21698175370693207, -0.28039711713790894, -0.12167363613843918, -0.46604949235916138, -0.25932088494300842, 
  0.4282512366771698, -0.1802976131439209, 0.17704570293426514, 0.49363550543785095, 0.017166782170534134, 0.17259246110916138, 0.014503740705549717, 0.030800335109233856, -0.22296789288520813, 0.18070212006568909, -0.14916279911994934, 0.20464852452278137, -0.46208363771438599, -0.14701201021671295, -0.36098131537437439, -0.5976874828338623, 0.080960854887962341, -0.48841696977615356, 
  0.11204564571380615, 0.24107241630554199, 0.13601449131965637, -0.080056861042976379, -0.15394854545593262, 0.12866669893264771, 0.038940619677305222, -0.16581113636493683, -0.08406144380569458, 0.013068857602775097, -0.21091179549694061, 0.21971890330314636, -0.11922842264175415, -0.051349982619285583, 0.02249535359442234, -0.37080535292625427, 0.55839753150939941, -0.33698993921279907, 
  -0.29091200232505798, 0.052258171141147614, -0.30827921628952026, -0.09226652979850769, -0.28616592288017273, 0.087763108313083649, -0.38795971870422363, 0.053391247987747192, -0.37364432215690613, -0.41842618584632874, -0.86166512966156006, -0.34100130200386047, -0.28251349925994873, -0.077935375273227692, -0.067952096462249756, 0.51923376321792603, -0.16933472454547882, 0.51862657070159912, 
  0.84605920314788818, 0.34573599696159363, 0.47248503565788269, -0.092853918671607971, -0.53200274705886841, 0.072922207415103912, 0.5220029354095459, 0.30214977264404297, 0.22168043255805969, 0.38703426718711853, 0.13258686661720276, 0.45944425463676453, 0.44392260909080505, -0.204183429479599, 0.42370694875717163, -0.0075567145831882954, -0.28083169460296631, 0.25554627180099487, 
  -0.28990375995635986, -0.16581183671951294, -0.0062654674984514713, -0.33422645926475525, 0.03464946523308754, -0.49015480279922485, 0.59753966331481934, -0.018002625554800034, 0.55233526229858398, 0.12118066847324371, 0.87865781784057617, 0.60298216342926025, 0.70304757356643677, 0.29574015736579895, -0.078137360513210297, 0.61636871099472046, 0.0067213186994194984, 0.25543034076690674, 
  -0.18800419569015503, -0.31540092825889587, -0.067764163017272949, -0.15086717903614044, -0.084344580769538879, -0.29197487235069275, -0.26029473543167114, -0.30655217170715332, -0.30132630467414856, 0.047005917876958847, -0.3197484016418457, -0.34640389680862427, 0.19114361703395844, -0.20924180746078491, -0.31309682130813599, 0.35033005475997925, -0.15696735680103302, -0.016608931124210358, 
  0.26186636090278625, -0.21110646426677704, -0.095551632344722748, 0.081014305353164673, 0.067143842577934265, 0.66657918691635132, -0.35126522183418274, 0.34778487682342529, -0.19816300272941589, -0.11156017333269119, -0.2568608820438385, -0.063231363892555237, 0.11533758789300919, 0.025581929832696915, -0.26101082563400269, -0.2786460816860199, -0.64251953363418579, -0.099080204963684082, 
  1.1245702505111694, -0.072110757231712341, 0.058143485337495804, 0.53619450330734253, 0.29891529679298401, 0.019862717017531395, -0.10960524529218674, 0.13691581785678864, 0.052114035934209824, 0.091463066637516022, 0.051301572471857071, -0.29358622431755066, -0.56394761800765991, 0.13286183774471283, -0.59914374351501465, -0.44765770435333252, -0.59939181804656982, -0.25027990341186523, 
  0.058362334966659546, 0.317220538854599, -0.15195547044277191, -0.19076187908649445, -0.37073266506195068, 0.13148078322410583, -0.36353465914726257, -0.08622819185256958, -0.28984296321868896, -0.2570425271987915, -0.81326240301132202, -0.22750897705554962, -0.11351796239614487, 0.41188573837280273, 0.66644197702407837, 0.5911213755607605, -0.15562325716018677, 0.424183189868927, 
  -0.14511816203594208, -0.30559989809989929, -0.26835131645202637, -0.16892294585704803, 0.11489365249872208, -0.21292302012443542, -0.25040411949157715, -0.19532927870750427, -0.17673513293266296, -0.39986613392829895, -0.90681350231170654, -0.27966231107711792, -0.13137158751487732, -0.015090804547071457, -0.10682344436645508, -0.10047176480293274, -0.25550550222396851, -0.21666255593299866, 
  0.12167380005121231, 0.50658923387527466, 0.69917237758636475, 0.63449448347091675, -0.14425545930862427, 0.084561571478843689, -0.25416174530982971, 0.1690601110458374, 0.002135109156370163, -0.18905168771743774, -0.14410308003425598, 0.17047373950481415, -0.44384145736694336, -0.17580285668373108, -0.5342789888381958, -0.4379698634147644, -0.46497774124145508, -0.30005559325218201, 
  -0.19032640755176544, -0.032308559864759445, 0.22642838954925537, -0.2277815043926239, 0.21247114241123199, 0.06261657178401947, 0.038153756409883499, 0.44574537873268127, 0.26126557588577271, 0.1707141250371933, -0.44032827019691467, 0.17628604173660278, -0.53624820709228516, -0.41828155517578125, -0.44601953029632568, -0.44860056042671204, -0.0175649244338274, -0.55504673719406128, 
  0.26272132992744446, 0.68363136053085327, 0.33000946044921875, 0.057028613984584808, -0.054237082600593567, 0.11404669284820557, -0.14291302859783173, -0.37932276725769043, -0.090030089020729065, -0.050237894058227539, -0.32587641477584839, -0.077153213322162628, -0.18369436264038086, 0.0047679133713245392, -0.22388213872909546, -0.4586663544178009, 0.078255914151668549, -0.56149393320083618, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,18 } };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,4 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,2,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,1,5 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension0, 72, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 120, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 800, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 80, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 12, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1440, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 80, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension8, 40, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 12, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 12, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = kTfLiteFloat32;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization.type = kTfLiteNoQuantization;

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = kTfLiteFloat32;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1003776_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1003776_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1003776_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1003776_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1003776_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
